name: ESLint analyze

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - 'assets/**'
      - 'config'
      - '.devcontainer.json'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'LICENSE'
      - 'README.md'
      - 'docker-compose.yml'
      - 'eslint.config.mjs'
      - 'index.html'
      - 'package-lock.json'
      - 'package.json'
      - 'style.css'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - 'assets/**'
      - 'config'
      - '.devcontainer.json'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'LICENSE'
      - 'README.md'
      - 'docker-compose.yml'
      - 'eslint.config.mjs'
      - 'index.html'
      - 'package-lock.json'
      - 'package.json'
      - 'style.css'

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: javascript-typescript
          build-mode: none
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ESLint
        run: |
          npm install eslint@9.38.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --config eslint.config.mjs
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true